### PR TITLE
NAS-117653 / 22.12 / Remove legacy behavior to auto-create SMB path

### PR DESCRIPTION
**Pull request by anodos325**
This removes a counter-intuitive behavior that has been in FreeNAS for a significant portion of its existence.

### CODE REVIEW

**Review by yocalebo — APPROVED** [review]

**Comment by yocalebo** [comment]
oops, wrong PR reviewed 😄

**Comment by anodos325** [comment]
Meh, this one is pretty trivial. I'll take it as tacit approval here.

**Comment by yocalebo** [comment]
retest this please

**Comment by yocalebo** [comment]
retest this please

**Comment by anodos325** [comment]
I need to update a test.

**Pull request merged**
