### PR TITLE
NAS-115240 / 22.12 / NAS-115240: JobSharedLock: use set() to track jobs

### PR DESCRIPTION
**Pull request by rkojedzinszky**

### CODE REVIEW

**Comment by themylogin** [comment]
Thank you for your contribution! Unfortunately, "somehow the same job entry enters the queue twice" is not a valid explanation for us so we need to investigate this deeper. What exact jobs did you have issues with?

**Comment by rkojedzinszky** [comment]
> Thank you for your contribution! Unfortunately, "somehow the same job entry enters the queue twice" is not a valid explanation for us so we need to investigate this deeper. What exact jobs did you have issues with?

I've modified JobSharedLock() to log add/remove operations, which results in the following output. Note that I am already using set() instead of list, but the double-entry can be observed:

```
lock[process_alerts      ]: removed  job=478  , m=alert.send_alerts    qlen=0, obj=<middlewared.job.Job object at 0x81f27c610>
lock[process_alerts      ]: adding   job=None , m=alert.process_alerts qlen=1, obj=<middlewared.job.Job object at 0x820858e20>
lock[process_alerts      ]: adding   job=480  , m=alert.process_alerts qlen=1, obj=<middlewared.job.Job object at 0x820858e20>
lock[process_alerts      ]: adding   job=481  , m=alert.send_alerts    qlen=2, obj=<middlewared.job.Job object at 0x81f124dc0>
lock[process_alerts      ]: removing job=480  , m=alert.process_alerts qlen=2, obj=<middlewared.job.Job object at 0x820858e20>
lock[process_alerts      ]: removed  job=480  , m=alert.process_alerts qlen=1, obj=<middlewared.job.Job object at 0x820858e20>
lock[process_alerts      ]: adding   job=481  , m=alert.send_alerts    qlen=1, obj=<middlewared.job.Job object at 0x81f124dc0>
lock[process_alerts      ]: removing job=481  , m=alert.send_alerts    qlen=1, obj=<middlewared.job.Job object at 0x81f124dc0>
```

`alert.process_alerts` is added twice.

**Comment by rkojedzinszky** [comment]
Anyway, if the double-enter will be eliminated, a set() is more suitable to keep track of unique elements in place of a list.

**Comment by themylogin** [comment]
Superseded by https://github.com/truenas/middleware/pull/8521

**Pull request closed without merging**
