### PR TITLE
NAS-116842 / 13.0 / fix regression syncing disks in 13

### PR DESCRIPTION
**Pull request by yocalebo**
Commit 6caafedae03ca3d62da7eb0f5ede76ca8b11f0f9 made it so that `disk.sync_all` was completely broken because it no longer worked with anything other than disks having partition labels written to them. This means the first disk that was manually wiped, caused all disks in the db to be expired and therefore not displayed in `disk.query`.

Fix 3 problems:
1. revert the problem commit
2. had an improper boolean logic check (`if this and that` changed to `if this and not that`)
3. remove the walrus operator `:=` and check for explicit `None` so `uuid` information is returned appropriately.

### CODE REVIEW

**Comment by themylogin** [comment]
The original code did not work well with disks that do not report serial numbers, did you test this case?

**Comment by themylogin** [comment]
@yocalebo I spent a lot of time fixing this and it was not the only issue. Do you want me to test this PR with disks that do not report serials or is it already tested?

**Comment by yocalebo** [comment]
> @yocalebo I spent a lot of time fixing this and it was not the only issue. Do you want me to test this PR with disks that do not report serials or is it already tested?

Sure you can test but be sure and test on physical hardware because the previous commit causes all disks to be removed from `disk.query`. Also the commit that caused the regression is for someone using truenas inside vmware which isn't really a supported configuration. As a matter of fact, most of the time where disks don't report serial numbers is when truenas is virtualized. So keep that in mind because I don't want to waste too much time on this "problem" since it effects only a small subset of users.

**Comment by william-gr** [comment]
Its not such a small subset, its pretty big actually, so I would prefer we don't regress on that either :P

**Comment by william-gr** [comment]
To put into perspective, we have 37.000+ VMWare Virtual disks reported in our usage stats.

**Pull request closed without merging**
