### PR TITLE
NAS-117563 / 23.10 / Use libzfs to get and set quotas

### PR DESCRIPTION
**Pull request by freqlabs**
rather than shelling out to the zfs command.

### CODE REVIEW

**Comment by freqlabs** [comment]
To test this we'll need to merge the py-libzfs PR first and wait for a new build to hit the API test runner.

**Comment by freqlabs** [comment]
More changes:
* Removed the percentage calculation, we don't need to send extra bytes when this value can be easily calculated client side

**Comment by freqlabs** [comment]
Setting quotas doesn't seem to work or I'm doing it wrong:
```
root@truenas[~]# midclt call pool.dataset.set_quota storage/test '[{"quota_type":"USEROBJ","id":1002,"quota_value":9999}]'
[EINVAL] pool_dataset_update.userobjquota@1002: Field was not expected
```

**Comment by anodos325** [comment]
> Setting quotas doesn't seem to work or I'm doing it wrong:
> 
> ```
> root@truenas[~]# midclt call pool.dataset.set_quota storage/test '[{"quota_type":"USEROBJ","id":1002,"quota_value":9999}]'
> [EINVAL] pool_dataset_update.userobjquota@1002: Field was not expected
> ```

You're no longer calling `zfs.dataset.set_quota` internal API. Did you replace it or just delete?

**Comment by freqlabs** [comment]
I deleted it. Setting quotas is just setting properties. We don't need to shell out to `zfs set` for that.

**Comment by anodos325** [comment]
set_quota was a wrapper around either updating dataset quota (through existing dataset API) or user quota.

**Comment by freqlabs** [comment]
* Added back `zfs.dataset.set_quota` to set the quotas because `zfs.dataset.update` validation rejects the userquota props

**Comment by freqlabs** [comment]
It works!
```
root@truenas[~]# midclt call pool.dataset.set_quota storage/test '[{"quota_type":"USEROBJ","id":1002,"quota_value":69420}]'
null
root@truenas[~]# midclt call pool.dataset.get_quota storage/test USER
[{"quota_type": "USER", "id": 1001, "used_bytes": 3488786944, "obj_used": 103885}, {"quota_type": "USER", "id": 0, "used_bytes": 2698000896, "obj_used": 83365, "name": "root"}, {"quota_type": "USER", "id": 1002, "obj_quota": 69420}]

**Review by yocalebo — APPROVED** [review]

**Comment by freqlabs** [comment]
The API tests passed.

**Comment by freqlabs** [comment]
backport

**Pull request merged**
