### PR TITLE
NAS-114415 / 22.12 / Custom ISO and Root Filesystem documentation

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by rick-mesta** [comment]
@themylogin: Please re-target this PR to `scale/angelfish` 🙏🏼

**Comment by william-gr** [comment]
No need, lets keep this for master please.

**Comment by pkgdemon** [comment]
retest this please

**Comment by william-gr** [comment]
This has been hanging for over half a year. Can we fix or close? @themylogin

**Comment by pkgdemon** [comment]
retest this please

**Comment by yocalebo** [comment]
@themylogin ping, what are we doing here?

**Pull request merged**
