### PR TITLE
Skip ALLOW test for NFS4 WRITE_ATTRIBUTES on SCALE

### PR DESCRIPTION
**Pull request by anodos325**
At this point, special handling of this permission is not
ipmlmented. Specifically, WRITE_DATA | WRITE_ATTRIBUTES are
required in order to alter timestamps. At this point no
adverse affect has been observed with SMB server and such
behavior is comparable with FreeBSD NFSv4 ACL implmenetation.
We can re-evaluate in future if it becomes a demonstrable
issue in real-life workloads, otherwise we'll keep
implementation simpler.

### CODE REVIEW

**Review by themylogin — COMMENTED** [review]
We can remove all `if scale` from this test, can't we?

**Comment by ericbsd** [comment]
> We can remove all `if scale` from this test, can't we?

I agree!

I am working on a PR that will remove scale from the master branch API tests

**Comment by anodos325** [comment]
> We can remove all `if scale` from this test, can't we?

Sounds like Eric just volunteered for me to delegate that to him :)

**Comment by ericbsd** [comment]
@anodos325  how do we process about that? We merged it and I make the changes on my branch?

**Review by ericbsd — APPROVED** [review]
LGTM

**Comment by anodos325** [comment]
Per discussion, will `if scale` in separate PR.

**Pull request merged**
