### PR TITLE
NAS-120020 / 23.10 / Apply some minor improvements to filter_list

### PR DESCRIPTION
**Pull request by anodos325**
Avoid unnecessary memory allocations when filtering.
Breaking this function apart improved readability
as well as improving performance in ad-hoc benchmarks by
approximately 25%.

### CODE REVIEW

**Review by themylogin — CHANGES_REQUESTED** [review]
This is a very important method, unit tests are needed and can be added easily

**Comment by anodos325** [comment]
> This is a very important method, unit tests are needed and can be added easily

We already have some unit tests. Are there any additional ones you think we need? Perhaps validation-side?

**Comment by yocalebo** [comment]
@themylogin all current CI tests pass for this
```
../../../usr/local/lib/python3.9/dist-packages/middlewared/pytest/unit/utils/test_filter_list.py::test__filter_list_equal PASSED [ 96%]
../../../usr/local/lib/python3.9/dist-packages/middlewared/pytest/unit/utils/test_filter_list.py::test__filter_list_starts PASSED [ 96%]
../../../usr/local/lib/python3.9/dist-packages/middlewared/pytest/unit/utils/test_filter_list.py::test__filter_list_ends PASSED [ 96%]
../../../usr/local/lib/python3.9/dist-packages/middlewared/pytest/unit/utils/test_filter_list.py::test__filter_list_regex_begins PASSED [ 96%]
../../../usr/local/lib/python3.9/dist-packages/middlewared/pytest/unit/utils/test_filter_list.py::test__filter_list_regex_contains PASSED [ 97%]
../../../usr/local/lib/python3.9/dist-packages/middlewared/pytest/unit/utils/test_filter_list.py::test__filter_list_gt PASSED [ 97%]
../../../usr/local/lib/python3.9/dist-packages/middlewared/pytest/unit/utils/test_filter_list.py::test__filter_list_gte PASSED [ 97%]
../../../usr/local/lib/python3.9/dist-packages/middlewared/pytest/unit/utils/test_filter_list.py::test__filter_list_lt PASSED [ 97%]
../../../usr/local/lib/python3.9/dist-packages/middlewared/pytest/unit/utils/test_filter_list.py::test__filter_list_lte PASSED [ 97%]
../../../usr/local/lib/python3.9/dist-packages/middlewared/pytest/unit/utils/test_filter_list.py::test__filter_list_in PASSED [ 98%]
../../../usr/local/lib/python3.9/dist-packages/middlewared/pytest/unit/utils/test_filter_list.py::test__filter_list_nin PASSED [ 98%]
../../../usr/local/lib/python3.9/dist-packages/middlewared/pytest/unit/utils/test_filter_list.py::test__filter_list_rin PASSED [ 98%]
../../../usr/local/lib/python3.9/dist-packages/middlewared/pytest/unit/utils/test_filter_list.py::test__filter_list_rnin PASSED [ 98%]
../../../usr/local/lib/python3.9/dist-packages/middlewared/pytest/unit/utils/test_filter_list.py::test__filter_list_OR_eq1 PASSED [ 98%]
../../../usr/local/lib/python3.9/dist-packages/middlewared/pytest/unit/utils/test_filter_list.py::test__filter_list_OR_eq2 PASSED [ 99%]
```

**Comment by themylogin** [comment]
@anodos325 yes, I am missing tests for various `options`

**Comment by anodos325** [comment]
> @anodos325 yes, I am missing tests for various `options`

Do you think we should also validate keys in options dict?

**Review by yocalebo — APPROVED** [review]

**Review by themylogin — APPROVED** [review]
Thank you!

**Pull request merged**
