### PR TITLE
NAS-119184 / 23.10 / Workaround https://github.com/vmware/pyvmomi/issues/993

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by themylogin** [comment]
time 0:30

**Review by ericbsd — APPROVED** [review]
LGTM

**Review by yocalebo — COMMENTED** [review]
Upstream has already fixed this? Have they just not published the latest release somewhere or something?

**Comment by themylogin** [comment]
@yocalebo yes, pip still has no fixed version. This is not publicly running code and I doubt there is any problem with sticking to an old version

**Review by yocalebo — APPROVED** [review]

**Pull request merged**
