### PR TITLE
NAS-113861 / 23.10 / SQLAlchemy 1.4 compatibility

### PR DESCRIPTION
**Pull request by themylogin**
These changes are incompatible with SQLAlchemy 1.3. TrueNAS SCALE uses SQLAlchemy 1.3, TrueNAS CORE 13 uses SQLAlchemy 1.4. This ticket should be merged once we update TrueNAS SCALE to the distribution that ships SQLAlchemy 1.4.

### CODE REVIEW

**Comment by themylogin** [comment]
backport

**Review by sonicaj — APPROVED** [review]

**Comment by rick-mesta** [comment]
@themylogin: Please re-target this PR to `scale/angelfish` 🙏🏼

**Comment by yocalebo** [comment]
@themylogin ping

**Comment by themylogin** [comment]
@yocalebo we'll merge this when python3-sqlalchemy shipped with our debian release gets updated to 1.4

**Pull request merged**
