### PR TITLE
NAS-119017 / 22.12 / Add glusterfs filesystem plugin

### PR DESCRIPTION
**Pull request by anodos325**
Use libgfapi python bindings to perform filesystem ops on glusterfs filesystem. This is less error-prone than relying on a fuse mount and gives us somewhat greater control and performance when doing recursive operations as well as a framework for testing the python bindings in our cluster API tests.

### CODE REVIEW

**Comment by anodos325** [comment]
needs docs

**Review by yocalebo — APPROVED** [review]
This looks good and docstrings are fantastic but I'll feel way more comfortable once we get tests in place 😄

**Comment by yocalebo** [comment]
Oops, fix the flake8 issue before merging please.

**Comment by yocalebo** [comment]
retest this please

**Pull request merged**
