### PR TITLE
NAS-121957 / 23.10 / Set proper homedir for built-in users

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by anodos325** [comment]
Needs commit message of some sort.

**Comment by anodos325** [comment]
Perhaps I'm missing something, but how does this fix case where DB insertion with wrong homedir has already occurred?

**Comment by themylogin** [comment]
> Needs commit message of some sort.

What is wrong with the current commit message?

> Perhaps I'm missing something, but how does this fix case where DB insertion with wrong homedir has already occurred?

This method updates built-in users database on every TrueNAS version update, including homedirs.

**Comment by yocalebo** [comment]
retest this please

**Comment by yocalebo** [comment]
retest this please

**Review by yocalebo — CHANGES_REQUESTED** [review]
While this might fix some, it doesn't fix all. For example, the `bin` user has `/` set as the home directory in the `/etc/passwd` db file. This is because that's the default on BSD* based systems, however, on linux its default is `/bin`. I think we should probably compare the passed file we ship with a stock debian install to make sure we've got them matched up as best as possible

**Comment by themylogin** [comment]
@yocalebo where does `/bin` user have `/` set as their home directory?

**Review by yocalebo — APPROVED** [review]

**Comment by themylogin** [comment]
time 2:00

**Pull request merged**
