### PR TITLE
NAS-114116 / 22.02 / Make minio console port configurable (migs are cherry-picked)

### PR DESCRIPTION
**Pull request by Qubad786**

### CODE REVIEW

**Comment by Qubad786** [comment]
debian: https://github.com/truenas/minio/pull/4

**Comment by themylogin** [comment]
@Qubad786 I don’t see how are these databases changes used by minio configuration generator?

**Comment by Qubad786** [comment]
@themylogin its utilized in minio debian here: https://github.com/truenas/minio/pull/4

**Review by themylogin — APPROVED** [review]
Uh sorry, forgot about that 😃

**Pull request merged**
