### PR TITLE
NAS-133120 / 25.04 / add name to PidEntry

### PR DESCRIPTION
**Pull request by yocalebo**
This adds the process name to `PidEntry` so that `get_pids` output is a bit more familiar to consumers.

Jira: https://ixsystems.atlassian.net/browse/NAS-133120

### CODE REVIEW

**Comment by themylogin** [comment]
Should we do this on-demand? Most of the time, it's not really needed.

**Comment by yocalebo** [comment]
> Should we do this on-demand? Most of the time, it's not really needed.

Sure, made some changes.

**Comment by themylogin** [comment]
I mean, it can be a `@cached_property` instead

**Comment by yocalebo** [comment]
> I mean, it can be a `@cached_property` instead

slots=True in the dataclass prevent easily using a `@cached_property` since the property is stored in the `__dict__` attribute by default. I'll see if there is an easy way around this.

**Comment by themylogin** [comment]
@yocalebo why is it needed?

**Comment by yocalebo** [comment]
> @yocalebo why is it needed?

The memory savings, and performance impact is non-trivial when using a non-slotted class.

**Review by themylogin — APPROVED** [review]

**Pull request merged**
