### PR TITLE
NAS-124613 / 24.04 / Expose credentials for the user who started the job

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by themylogin** [comment]
time 1:00

**Comment by themylogin** [comment]
http://ci.tn.ixsystems.com/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/API%20Tests%20-%20TrueNAS%20SCALE%20with%20middleware%20reinstalled%20from%20a%20branch%20Incremental/1241/

**Comment by yocalebo** [comment]
@anodos325 since you requested, would like your review

**Comment by themylogin** [comment]
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/API%20Tests%20-%20TrueNAS%20SCALE%20with%20middleware%20reinstalled%20from%20a%20branch%20Incremental/1251/

**Review by anodos325 — APPROVED** [review]

**Comment by anodos325** [comment]
That looks really good. Thanks Vladimir.

**Comment by themylogin** [comment]
UI ticket https://ixsystems.atlassian.net/browse/NAS-124841

**Pull request merged**
