### PR TITLE
NAS-103891 / 21.06 / ipmi.clear_sel

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by william-gr** [comment]
How can we read SEL ?

**Review by yocalebo — CHANGES_REQUESTED** [review]
This will not work on X series based devices since IPMI device is not accessible from the host OS.

**Comment by yocalebo** [comment]
> This will not work on X series based devices since IPMI device is not accessible from the host OS.

Meh, I see this is just adding a method to be called.

**Comment by themylogin** [comment]
@william-gr alert source creates alerts for new events. Do we need to show them all somewhere?

**Comment by william-gr** [comment]
@themylogin Yes, if I get an alert saying SEL is full, I want a way to retrieve them all first

**Review by william-gr — APPROVED** [review]

**Review by yocalebo — APPROVED** [review]

**Comment by bvasilenko** [comment]
@themylogin Could you pls show an example of back-end response from `ipmi.query_sel` ? I'm integrating this into WebUI

**Comment by themylogin** [comment]
@bvasilenko please ask QE team for a hardware access to a machine that has IPMI SEL events present and SCALE installed.

**Pull request merged**
