### PR TITLE
NAS-114479 / 23.10 / Shrink swap when formatting a disk in `pool.replace` to fit a data pa…

### PR DESCRIPTION
**Pull request by themylogin**
…rtiton of required size

### CODE REVIEW

**Comment by themylogin** [comment]
time 4:00

**Review by yocalebo — CHANGES_REQUESTED** [review]
The test will never pass on our HA VMs so we should only run it on non-HA.

**Comment by themylogin** [comment]
@yocalebo this file has 
```
pytestmark = [
    pytest.mark.skipif(dev_test, reason='Skipping for test development testing'),
    pytest.mark.skipif(ha, reason='Skipping for HA testing'),
]
```

**Comment by themylogin** [comment]
@yocalebo ☹️

**Review by yocalebo — APPROVED** [review]

**Comment by themylogin** [comment]
backport

**Pull request merged**
