### PR TITLE
NAS-111654 / 21.08 / Make sure coredump dir is not mounted when switching system dataset

### PR DESCRIPTION
**Pull request by sonicaj**

### CODE REVIEW

**Review by rick-mesta — APPROVED** [review]
lgtm; @themylogin would you please also take a look ?

**Comment by freqlabs** [comment]
The problem directory was /var/db/system so it's not clear how this helps. Is there a symlink somewhere?

**Review by themylogin — APPROVED** [review]

**Comment by rick-mesta** [comment]
@sonicaj: I think @freqlabs raised a good question - what was the resolution to that ?

**Comment by sonicaj** [comment]
@freqlabs @rick-mesta it was something similar to the following flow:
```
❯ mount -t zfs evo/parent /test
❯ mount -t zfs evo/parent/child /test/cores
❯ mount --bind /test/cores /anotherdir
❯ df -h /anotherdir
Filesystem        Size  Used Avail Use% Mounted on
evo/parent/child   37G  128K   37G   1% /anotherdir
❯ umount -f evo/parent/child
❯ df -h /anotherdir
Filesystem                                   Size  Used Avail Use% Mounted on
boot-pool/ROOT/21.08-MASTER-20210804-204659   24G  2.9G   21G  13% /
❯
❯ df -h /test/cores
Filesystem        Size  Used Avail Use% Mounted on
evo/parent/child   37G  128K   37G   1% /test/cores
❯ umount -f evo/parent
umount: /test: target is busy.
```

**Comment by sonicaj** [comment]
We have it passing now ;) ( https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/API%20Tests%20-%20TrueNAS%20SCALE%20(Incremental)/6677/console )
```
api2/test_007_pool_dataset_encryption.py::test_032_delete_pool PASSED    [  5%]
```

**Comment by freqlabs** [comment]
Excellent, the bind mount wasn't present on my machine (running an older nightly). That certainly explains it!

**Pull request merged**
