### PR TITLE
NAS-126058 / 24.04 / Fix roles

### PR DESCRIPTION
**Pull request by themylogin**
* Credentials had all roles by default. This will be a huge security risk if we start using. roles to determine if users can execute certain things. We should default to `False`, credentials must have roles explicitly.
* As a consequence, token credentials (all WebUI sessions) had all roles, including `READONLY` role. This made the middleware redact all private variables for all return values for WebUI even if we were root.
* `has_role("READONLY")` is a weird way to determine whether we should redact private variables for return values. Should we just only show them to full admins?
* As for the original issue (SMART test schema being inconsistent with the actual return value and failing to redact private variables), let's fix this once we have SMART tests available to non-privileged users.

### CODE REVIEW

**Comment by themylogin** [comment]
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/API%20Tests%20-%20TrueNAS%20SCALE%20with%20middleware%20reinstalled%20from%20a%20branch%20Incremental/1591/

**Comment by themylogin** [comment]
@anodos325 @yocalebo what do you think about #3?

**Comment by themylogin** [comment]
@anodos325 I agree with you, done.

**Comment by themylogin** [comment]
@yocalebo @anodos325 sorry, one more thing. I also removed redacting out private fields for non-user access (e.g. API keys)

**Comment by themylogin** [comment]
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/API%20Tests%20-%20TrueNAS%20SCALE%20with%20middleware%20reinstalled%20from%20a%20branch%20Incremental/1592/

**Comment by anodos325** [comment]
> @yocalebo @anodos325 sorry, one more thing. I also removed redacting out private fields for non-user access (e.g. API keys)

That's reasonable, otherwise we would break existing consumers.

**Review by anodos325 — APPROVED** [review]

**Review by yocalebo — APPROVED** [review]

**Comment by themylogin** [comment]
time 0:30

**Pull request merged**
