### PR TITLE
NAS-111020 / 22.12 / Add USB Passthrough support

### PR DESCRIPTION
**Pull request by sonicaj**

### CODE REVIEW

**Review by themylogin — APPROVED** [review]

**Comment by ServusNL** [comment]
Hey! I updated to beta (TrueNAS-SCALE-22.12-BETA.1) mainly for this feature, USB is not showing up tough...
image
Should I open an issue?

**Comment by sonicaj** [comment]
> Hey! I updated to beta (TrueNAS-SCALE-22.12-BETA.1) mainly for this feature, USB is not showing up tough... image Should I open an issue?

@ServusNL please track https://ixsystems.atlassian.net/browse/NAS-118325 for UI support. Thanks!

**Comment by kiler129** [comment]
> Hey! I updated to beta (TrueNAS-SCALE-22.12-BETA.1) mainly for this feature, USB is not showing up tough...
> image
> Should I open an issue?

You can use the API; as a reproducer for one of the issues I posted the steps: https://ixsystems.atlassian.net/browse/NAS-118387

**Comment by ServusNL** [comment]
> > Hey! I updated to beta (TrueNAS-SCALE-22.12-BETA.1) mainly for this feature, USB is not showing up tough...
> 
> 
> 
> @ServusNL You can use the API; as a reproducer for one of the issues I posted the steps: https://ixsystems.atlassian.net/browse/NAS-118387

Thanks! Sounds promising, when I open the link I get the message the page does not exist though.

**Comment by kiler129** [comment]
> > > Hey! I updated to beta (TrueNAS-SCALE-22.12-BETA.1) mainly for this feature, USB is not showing up tough...
> > 
> > 
> > @ServusNL You can use the API; as a reproducer for one of the issues I posted the steps: https://ixsystems.atlassian.net/browse/NAS-118387
> 
> Thanks! Sounds promising, when I open the link I get the message the page does not exist though.

Hm, it's possible issues are private until triaged; let me repost here:

1. Go to `https://<TNS_IP>/api/docs/`
2. Move to RESTful 2.0 tab
3. Authorize on the top right
4. List your VMs using `/vm` action and save your VM id
5. List USB devices using `/vm/device/usb_passthrough_choices` and get your device name (e.g. `usb_1_4`)
6. Add USB to vm using `/vm/device` (the POST one) with the following data:

(fill-in the data below as needed above)
```json
{
  "dtype": "USB",
  "vm": 1,
  "attributes": {
    "device": "usb_1_4"
  }
}
```

7. Check USB devices attached to a VM using `/vm/id/1`, USB will be listed with the `usb_1_4` assignment:
```json
{
  "id": 1,
  "name": "test-vm",
  //<removed for readability>
  "devices": [
    //<removed for readability>
    {
      "id": 8,
      "dtype": "USB",
      "attributes": {
        "device": "usb_1_4"
      },
      "order": 1002,
      "vm": 1
    }
  ],
  "status": {
    "state": "STOPPED",
    "pid": null,
    "domain_state": "SHUTOFF"
  }
}
```

**HOWEVER**, *here be dragons* warning: this doesn't seem to be stable. 

This feature, at least in my opinion has a major design flaw: it targets device by it's port and location. When the device reconnects it will not be visible in the VM. Similarly if you change USB port the device will not be visible and you may accidentally redirect a different device. On some machines the enumeration of devices isn't stable. There is no way to pass a particular port. In addition, unplugging the device and replugging it sometimes crashes my qemu with a segfault.
If this is shipped in such a state this is going to be bad :D

**Comment by ServusNL** [comment]
> > > > Hey! I updated to beta (TrueNAS-SCALE-22.12-BETA.1) mainly for this feature, USB is not showing up tough...
> > > 
> > > 
> > > @ServusNL You can use the API; as a reproducer for one of the issues I posted the steps: https://ixsystems.atlassian.net/browse/NAS-118387
> > 
> > 
> > Thanks! Sounds promising, when I open the link I get the message the page does not exist though.
> 
> Hm, it's possible issues are private until triaged; let me repost here:
> 
> 1. Go to `https://<TNS_IP>/api/docs/`
> 2. Move to RESTful 2.0 tab
> 3. Authorize on the top right
> 4. List your VMs using `/vm` action and save your VM id
> 5. List USB devices using `/vm/device/usb_passthrough_choices` and get your device name (e.g. `usb_1_4`)
> 6. Add USB to vm using `/vm/device` (the POST one) with the following data:
> 
> (fill-in the data below as needed above)
> 
> ```json
> {
>   "dtype": "USB",
>   "vm": 1,
>   "attributes": {
>     "device": "usb_1_4"
>   }
> }
> ```
> 
>  7. Check USB devices attached to a VM using `/vm/id/1`, USB will be listed with the `usb_1_4` assignment:
> 
> ```json
> {
>   "id": 1,
>   "name": "test-vm",
>   //<removed for readability>
>   "devices": [
>     //<removed for readability>
>     {
>       "id": 8,
>       "dtype": "USB",
>       "attributes": {
>         "device": "usb_1_4"
>       },
>       "order": 1002,
>       "vm": 1
>     }
>   ],
>   "status": {
>     "state": "STOPPED",
>     "pid": null,
>     "domain_state": "SHUTOFF"
>   }
> }
> ```
> 
> **HOWEVER**, _here be dragons_ warning: this doesn't seem to be stable.
> 
> This feature, at least in my opinion has a major design flaw: it targets device by it's port and location. When the device reconnects it will not be visible in the VM. Similarly if you change USB port the device will not be visible and you may accidentally redirect a different device. On some machines the enumeration of devices isn't stable. There is no way to pass a particular port. In addition, unplugging the device and replugging it sometimes crashes my qemu with a segfault. If this is shipped in such a state this is going to be bad :D

Thanks for your explanation, work like a charm except for your " dragons warning". I completely agree with your statement: "If this is shipped in such a state this is going to be bad". You would expect the mounting would be done by "id" like TrueChart is allowing for it's docker containers, like: /dev/serial/by-id/usb-xxx_USB_Serial-xx00-port0

**Comment by kiler129** [comment]
> You would expect the mounting would be done by "id" like TrueChart is allowing for it's docker containers, like: /dev/serial/by-id/usb-xxx_USB_Serial-xx00-port0

This would be great... EXCEPT USB S/N are somewhat bogus on many devices unlike SCSI ones. IIRC from messing with Linux USB drivers the stack even includes a provisioning to generating random S/Ns for USB devices. There are many USB devices with all-zero S/N or duplicated ones like `1234567890`. This is why unfortunately USB passthrough is a can of worms with no single solution being without problems :D

**Pull request merged**
