### PR TITLE
NAS-115947 / 13.0 / Ignore I101 in flake8 linter

### PR DESCRIPTION
**Pull request by anodos325**

### CODE REVIEW

**Review by themylogin — CHANGES_REQUESTED** [review]
Just remove `pip install flake8 flake8-import-order` above instead

**Comment by anodos325** [comment]
To clarify, you're basically wanting to revert:
```
commit 977a78c6d9061d0d00c1044f1e9092a7c5424758
Author: themylogin <themylogin@gmail.com>
Date:   Mon Mar 14 20:22:39 2022 +0400

    Employ `flake8-import-order` to ensure correct import orders according to PEP8
    
    (cherry picked from commit a6d29fb4c7d68d1d9c58b0b2a2a1de5547a80fac)

```

?

**Comment by themylogin** [comment]
@anodos325 I don't want it, but if you don't want these checks in 13.0 PRs, that'll be fine by me.

**Comment by anodos325** [comment]
Changed to revert the linter rule added.

**Review by yocalebo — APPROVED** [review]

**Pull request merged**
