### PR TITLE
NAS-109476 / 21.06 / Replication name regex

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Review by yocalebo — COMMENTED** [review]
Is the migration supposed to be dropping the fiber channel table?

**Comment by yocalebo** [comment]
> @yocalebo it seems that this table is not defined anymore, I've thought you dropped it while moving enterprise plugins to the main tree. Is this an error?

I can't remember but FC hasn't been touched on SCALE, yet so this is fine removing it.

**Review by yocalebo — APPROVED** [review]

**Comment by william-gr** [comment]
@yocalebo @themylogin if we drop fiber channel table, how do we migrate from CORE/Enterprise? :)

**Comment by themylogin** [comment]
@william-gr will we need data from this table later?

**Comment by william-gr** [comment]
I dont know how FC works in Linux, but I imagine so?

**Pull request merged**
