### PR TITLE
NAS-114237 / 13.0 / Run `geom.scan` in `disk.sync_zfs_guid` to ensure newly created gptid visibility

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by themylogin** [comment]
time 03:00

**Review by yocalebo — CHANGES_REQUESTED** [review]
Since this is `truenas/13.0-stable` there shouldn't be a need for the `if osc` checks, right?

Also, on a system with 1k disks, when the zpool is created it will now run `kern.geom.confxml` 1k times which is going to cause `middlewared` to fall over so this won't work.

**Comment by themylogin** [comment]
@yocalebo why will it run `kern.geom.confxml` 1k times? This method is called once per pool configuration change, not once per disk.

**Comment by yocalebo** [comment]
> @yocalebo why will it run `kern.geom.confxml` 1k times? This method is called once per pool configuration change, not once per disk.

It's called once per disk when a zpool is created.

**Comment by themylogin** [comment]
> It's called once per disk when a zpool is created.

Who is the caller?

I created a pool with 2 2-way mirror vdevs, here is what happened:
```
[2022/01/18 05:52:00] (DEBUG) EtcService.generate():381 - No new changes for /etc/fstab
[2022/01/18 05:52:00] (DEBUG) middlewared.plugins.disk_.zfs_guid.hook():82 - calling from post_create_or_update
[2022/01/18 05:52:00] (DEBUG) middlewared.plugins.disk_.zfs_guid.sync_zfs_guid():24 - sync_zfs_guid called
[2022/01/18 05:52:01] (DEBUG) EtcService.generate():381 - No new changes for /etc/local/collectd.conf
[2022/01/18 05:52:01] (DEBUG) middlewared.dumpdev_configure():24 - Configured "/dev/ada4p1" device for crash dumps.
[2022/01/18 05:52:10] (DEBUG) EtcService.generate():381 - No new changes for /etc/local/collectd.conf
[2022/01/18 05:52:10] (DEBUG) EtcService.generate():381 - No new changes for /etc/local/smb4.conf
[2022/01/18 05:52:10] (DEBUG) EtcService.generate():381 - No new changes for /etc/security/pam_winbind.conf
[2022/01/18 05:52:11] (DEBUG) EtcService.generate():381 - No new changes for /etc/local/smbusername.map
[2022/01/18 05:52:11] (DEBUG) EtcService.generate():381 - No new changes for /etc/crontab
[2022/01/18 05:52:11] (DEBUG) EtcService.generate():381 - No new changes for /etc/group
[2022/01/18 05:52:11] (DEBUG) EtcService.generate():381 - No new changes for /etc/master.passwd
[2022/01/18 05:52:12] (WARNING) SMBService.validate_groupmap_hwm():210 - TDB maintenace failed: a bytes-like object is required, not 'NoneType'
[2022/01/18 05:52:12] (DEBUG) EtcService.generate():381 - No new changes for /etc/local/smb4_share.conf
```

**Comment by themylogin** [comment]
time 0:45

**Comment by rick-mesta** [comment]
@yocalebo / @themylogin: have the issues here been resolved ? Is this bad boy good to merge ? (reminder: freeze for 13.0-BETA.1 is on Jan/19/2022)

**Comment by yocalebo** [comment]
> @yocalebo / @themylogin: have the issues here been resolved ? Is this bad boy good to merge ? (reminder: freeze for 13.0-BETA.1 is on Jan/19/2022)

No, now on HA systems we will run `kern.geom.confxml` twice on every failover event for every pool being imported.

**Comment by yocalebo** [comment]
@themylogin this is what I'm seeing on zpool import (seems like duplicate events are generated via devd but now we're calling `geom.scan` which is going to be painful.
```
[2022/01/18 13:36:51] (DEBUG) middlewared.devd_zfs_hook():59 - in devd_zfs_hook
[2022/01/18 13:36:51] (DEBUG) middlewared.devd_zfs_hook():60 - data: {'system': 'ZFS', 'subsystem': 'ZFS', 'type': 'sysevent.fs.zfs.config_sync', 'version': '0', 'class': 'sysevent.fs.zfs.config_sync', 'pool': 'bigboi', 'pool_guid': '10693373528742427180', 'pool_state': '0', 'pool_context': '0', 'time': '00000016425418110000000963360208', 'eid': '1651'}
[2022/01/18 13:36:52] (DEBUG) middlewared.devd_zfs_hook():59 - in devd_zfs_hook
[2022/01/18 13:36:52] (DEBUG) middlewared.devd_zfs_hook():60 - data: {'system': 'ZFS', 'subsystem': 'ZFS', 'type': 'sysevent.fs.zfs.config_sync', 'version': '0', 'class': 'sysevent.fs.zfs.config_sync', 'pool': 'bigboi', 'pool_guid': '10693373528742427180', 'pool_state': '0', 'pool_context': '0', 'time': '00000016425418120000000205474781', 'eid': '1654'}
```

**Comment by yocalebo** [comment]
Just to give a little more context, the reason why I'm bringing this up is because there is another ticket for 13 for decreasing failover time. The ticket was on the OS side of things, but it was noticed that `kern.geom.confxml` takes up 20% of CPU time during failover. With these changes, it's going to only make it worse.

**Comment by themylogin** [comment]
@yocalebo ok, I moved `geom.scan` to be after `pool.format_disks`, this specific case works fine that way too

**Comment by yocalebo** [comment]
> @yocalebo ok, I moved `geom.scan` to be after `pool.format_disks`, this specific case works fine that way too

So here is the fun part. The problem this tries to fix has already been resolved in the other PR: https://github.com/truenas/middleware/pull/8149 with this commit specifically: https://github.com/truenas/middleware/pull/8149/commits/9ff08930d96784654d912663b946e37569ffcb61

**Comment by themylogin** [comment]
@yocalebo `pool.transform_topology` uses `disk.label_to_dev` and `disk.label_to_disk` which use `disk.label_to_dev_disk_cache`, I don't see any of this affected by `geom.cache` plugin, or am I missing something?

**Comment by yocalebo** [comment]
> @yocalebo `pool.transform_topology` uses `disk.label_to_dev` and `disk.label_to_disk` which use `disk.label_to_dev_disk_cache`, I don't see any of this affected by `geom.cache` plugin, or am I missing something?

Fix here: https://github.com/truenas/middleware/pull/8149/commits/da1b6516ca4bce4fc0f577c63bcd05732870555e

**Comment by themylogin** [comment]
Cool, let me check that your branch fixes this issue

**Comment by themylogin** [comment]
#8149 fixes this

**Pull request closed without merging**
