### PR TITLE
Remove create_subprocess_exec from loop monitor

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Review by yocalebo — CHANGES_REQUESTED** [review]
Hiding this prevents us from seeing relevant messages about threads that are taking forever. For example, the smartctl related messages are valid and point to the fact that we have a problem. I don't think hiding this does any good.

**Comment by themylogin** [comment]
@yocalebo we are not hiding it, we just display `create_subprocess_exec seems to be blocking event loop` instead of a full traceback of where exactly it is blocking (`subprocess` module is performing `fork`/`exec` calls on main loop, not out problem to fix). Also what does this have to do with `smartctl`?

**Comment by yocalebo** [comment]
@themylogin why hide the traceback that shows exactly where the problem is? Not every system is going to have a slow boot-pool. Furthermore, `subprocess` is our problem because the main event loop doesn't just fork/exec by itself. I brought up `smartctl` as an example because if you look at the `common/smart/smartctl.py` plugin you will see that we are the ones causing lock contention and overloading the main event loop because we're fork/exec'ing for every disk on the system. This doesn't scale and is already a problem on a system with 50+ disks. If I'm understanding this change, you're going to be hiding the traceback that shows where we're at when the main event loop is being blocked. If so, then I don't agree with this change.

**Comment by themylogin** [comment]
@yocalebo you are correct, we are losing debug information with this approach. What would you say now? It will print
```
[2021/11/16 08:49:19] (WARNING) middlewared._loop_monitor_thread():1621 - Task seems blocked:
  File "/usr/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1893, in _run_once
    def _set_coroutine_origin_tracking(self, enabled):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1701, in __initialize
    await self.__plugins_setup(setup_funcs)
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 978, in __plugins_setup
    await call
  File "/usr/lib/python3/dist-packages/middlewared/plugins/ipmi.py", line 221, in setup
    await run('ipmitool', 'lan', 'print', str(i))
  File "/usr/lib/python3/dist-packages/middlewared/utils/__init__.py", line 50, in run
    proc = await asyncio.create_subprocess_exec(*args, **kwargs)
  File "/usr/lib/python3.9/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  ... + 10 lines below ...
```

**Review by yocalebo — APPROVED** [review]
Yep, that looks good to me. Thanks!

**Comment by dabrahams** [comment]
I am getting these new messages quite a lot, e.g.

```

[2022/12/14 11:56:39] (WARNING) middlewared._loop_monitor_thread():1490 - Task seems blocked:
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/middlewared/plugins/cloud_sync.py", line 413, in rclone_check_progress
    job.set_progress(min(progresses), ', '.join(filter(None, [transferred1, transferred2, checks])))
  File "/usr/local/lib/python3.9/site-packages/middlewared/job.py", line 306, in set_progress
    self.middleware.send_event('core.get_jobs', 'CHANGED', id=self.id, fields=encoded)
  File "/usr/local/lib/python3.9/site-packages/middlewared/main.py", line 1355, in send_event
    wsclient.send_event(name, event_type, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/middlewared/main.py", line 258, in send_event
    self._send(event)
  File "/usr/local/lib/python3.9/site-packages/middlewared/main.py", line 96, in _send
    asyncio.run_coroutine_threadsafe(self.response.send_str(json.dumps(data)), loop=self.loop)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 933, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 797, in call_soon_threadsafe
    self._write_to_self()
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 140, in _write_to_self
    csock.send(b'\0')
```
and 

```
2022/12/15 09:46:43] (WARNING) middlewared._loop_monitor_thread():1538 - Task seems blocked:
  File "/usr/local/bin/middlewared", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/middlewared/main.py", line 1719, in main
    Middleware(
  File "/usr/local/lib/python3.9/site-packages/middlewared/main.py", line 1555, in run
    self.loop.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/middlewared/plugins/cloud_sync.py", line 403, in rclone_check_progress
    job.logs_fd.write(result.encode("utf-8", "ignore"))
```

How should I interpret them? Is this something I can troubleshoot?

**Comment by themylogin** [comment]
@dabrahams if it does not affect anything else then no

**Comment by dabrahams** [comment]
@themylogin it's hard for me to tell if it affects anything else.  I started looking at logs because of [this issue](https://www.truenas.com/community/threads/cloudsync-seems-to-have-started-over.106118/).  Do you think it's unconnected to these diagnostics?

**Pull request merged**
