### PR TITLE
NAS-112081 / 21.10 / Ignore deletion of hidden daatset clones such as `%recv` dataset crea…

### PR DESCRIPTION
**Pull request by themylogin**
…ted by replication

### CODE REVIEW

**Review by rick-mesta — APPROVED** [review]
lgtm: @yocalebo / @sonicaj / @anodos325 - I'd appreciate another pair of eyes 👀 on this bad boy, as it'll be merged 🤞🏼 into 21.08

**Review by yocalebo — COMMENTED** [review]
Does zettarepl have a list of names it uses for hidden clones?

**Comment by themylogin** [comment]
@yocalebo zettarepl does not create hidden clones implicitly, ZFS does it itself. I am not aware of any other hidden clones besides `%recv` but `%` is not allowed in the dataset name so it should be fine.

**Review by yocalebo — APPROVED** [review]

**Comment by rick-mesta** [comment]
Thx @yocalebo 🎉

**Pull request merged**
