### PR TITLE
NAS-118123 / 22.12 / Flush alerts to the database immediately after deleting oneshot alerts

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by themylogin** [comment]
time 3:00

**Review by yocalebo — CHANGES_REQUESTED** [review]
This means on every `alert.oneshot_delete, klass` we're going to empty the database and regenerate everything.

Can we not pass the `klass` to `flush_alerts` and only remove entries from the db that match that `klass` or something similar?

**Comment by themylogin** [comment]
@yocalebo oneshot alert deletions, on average, do not happen more often than flush_alerts (which is performed every hour), hence, I don't see any reason that we need a more efficient `flush_alerts` implementation because of this change. However, I agree that we can have more efficient `flush_alerts` implementation in general, but can we do this in a separate ticket?

**Comment by yocalebo** [comment]
Sure sounds good!

**Review by yocalebo — APPROVED** [review]

**Pull request merged**
