### PR TITLE
NAS-127771 / 24.10 / Fix `KeyError` in `rdma.get_link_choices`

### PR DESCRIPTION
**Pull request by themylogin**
```
  File "/usr/lib/python3/dist-packages/middlewared/plugins/rdma/rdma.py", line 69, in get_link_choices
    result.append({'rdma': link['ifname'], 'netdev': link['netdev']})
                                                     ~~~~^^^^^^^^^^
KeyError: 'netdev'
```

### CODE REVIEW

**Comment by themylogin** [comment]
@bmeagherix however, I am not sure what does the absence of this key really mean, should this may be handled  differently?

**Comment by themylogin** [comment]
time 0:20

**Review by bmeagherix — APPROVED** [review]
Thanks for the coded change.

I _would_ like to know more details about the device in question ... what type of RDMA capable interface is **not** providing a `netdev`.

Can you provide details?

It also would be good to see the output from `rdma link` and `rdma dev`, and grep output from _/var/log/kern.log_ pertaining to the device.

**Comment by themylogin** [comment]
@bmeagherix can you please ask the user in the issue comments? He could not attach a debug because his system was not booting due to this issue.

**Pull request merged**
