### PR TITLE
NAS-118571 / 22.12 / Fix used ports output when load balancer services are used

### PR DESCRIPTION
**Pull request by Qubad786**
## Context

When `LoadBalancer` type services are used with apps,system was not accounting for those services when determining `used_ports` of an application.

### CODE REVIEW

**Review by yocalebo — APPROVED** [review]

**Review by Ornias1993 — COMMENTED** [review]
There is one slight mistake here:
This should *only* be done when the default LoadBalancer "Integrated Loadbalancer"-checkbox, is enabled.

Non-default loadbalancers, such as metallb, might (and often do) use seperate IP's for seperate services.

For example:
With MetalLB, one can have 3 webservers using port 80, each with a different IP that the host has no idea about.

This version of the PR, would lead to issues in those cases... as the validator, that also uses this code portion, thinks the port is "already in use"

**Review by yocalebo — CHANGES_REQUESTED** [review]
@Ornias1993 thanks for the input. @Qubad786 can you investigate this scenario?

**Comment by Ornias1993** [comment]
> @Ornias1993 thanks for the input. @Qubad786 can you investigate this scenario?

No problem :)

**Review by Ornias1993 — COMMENTED** [review]
Yeah that should work nicely.
In the future, clustering etc, we *might* want to revisit, but for now this is more than fine :)

**Review by yocalebo — APPROVED** [review]

**Pull request merged**
