### PR TITLE
Use `secrets` instead of `random`

### PR DESCRIPTION
**Pull request by oittaa**
Since Python 3.6 `secrets` has been the recommended module for creation of random values that might be security critical. https://docs.python.org/3/library/secrets.html

### CODE REVIEW

**Comment by oittaa** [comment]
After you've tested this, I would highly recommend backporting this since those `random` generated auth tokens aren't that difficult to guess if you know an approximate time of creation.

**Comment by yocalebo** [comment]
> After you've tested this, I would highly recommend backporting this since those `random` generated auth tokens aren't that difficult to guess if you know an approximate time of creation.

@oittaa thanks again for pointing out the obvious and even offering a patch. If you don't mind, I'm going to open up a ticket for this problem and I'd like to push a PR that does essentially what you've done, however, I'd like to make a few general use functions that can be imported and used everywhere instead of doing `import secrets` in each module. We actually already have a general use function in `middlewared.utils.generate` but it's also using `random` module. 😄

**Comment by oittaa** [comment]
Sounds good to me!

**Comment by yocalebo** [comment]
@oittaa thanks again for the contribution. I'm going to close this in favor of https://github.com/truenas/middleware/pull/8829

**Pull request closed without merging**
