### PR TITLE
NAS-114305 / 22.12 / add cancel_rollback to interface API

### PR DESCRIPTION
**Pull request by yocalebo**
Requested by front-end team

### CODE REVIEW

**Review by themylogin — CHANGES_REQUESTED** [review]
This code is no different from `checkin`, what is its purpose?

**Comment by yocalebo** [comment]
> This code is no different from `checkin`, what is its purpose?

There is a difference, it doesn't remove the `_original_datastores` variable.

**Review by themylogin — CHANGES_REQUESTED** [review]
@yocalebo so the idea is to stop timer but allow later manual rollback?

In this case, can we please re-use this code which is already repeated in this file twice?

**Comment by yocalebo** [comment]
> @yocalebo so the idea is to stop timer but allow later manual rollback?
> 
> In this case, can we please re-use this code which is already repeated in this file twice?

The ticket that this is linked to has all those details.

**Comment by themylogin** [comment]
Thank you.

Code reuse proposal still stands

**Review by themylogin — APPROVED** [review]

**Pull request merged**
