### PR TITLE
NAS-111696 / 12.0 / dont call system.info in enclosure plugin

### PR DESCRIPTION
**Pull request by yocalebo**
While steps have been taken to speed up `system.info`, it's still expensive. Especially on large/busy systems. Furthermore, the enclosure plugin only needs the `system-product-name` from the dmi information. `system.dmidecode_info` is cached at first boot and far less expensive than `system.info` so use it instead in the enclosure plugin.

### CODE REVIEW

**Review by rick-mesta — APPROVED** [review]
LGTM 👍🏼

**Comment by rick-mesta** [comment]
@themylogin: ping

**Review by themylogin — APPROVED** [review]

**Comment by rick-mesta** [comment]
@themylogin: Thx Vlad 👍🏼

**Comment by themylogin** [comment]
backport

**Pull request merged**
