### PR TITLE
NAS-109700 / 21.04 / Support mailcfg[fromname]

### PR DESCRIPTION
**Pull request by MarkBarbieri**

### CODE REVIEW

**Comment by william-gr** [comment]
ok to test

**Review by themylogin — CHANGES_REQUESTED** [review]
@MarkBarbieri I think it'll be better to remove that `if mailcfg['fromemail'] != '':` altogether. `mail.send` puts correct `From` header automatically, it just seems to be overwritten with incorrect `From` supplied in `extra_headers`. Can you change that and test on your test case please?

**Comment by MarkBarbieri** [comment]
> @MarkBarbieri I think it'll be better to remove that `if mailcfg['fromemail'] != '':` altogether. `mail.send` puts correct `From` header automatically, it just seems to be overwritten with incorrect `From` supplied in `extra_headers`. Can you change that and test on your test case please?

Good, call.  That works well.

So all this can go.  I'll add a commit to this PR
```
53d52
<         mailcfg = c.call('mail.config')
63,67d61
<
<         if mailcfg['fromemail'] != '':
<             margs['extra_headers'].update({
<                 'From': mailcfg['fromemail']
<             })
```

**Review by themylogin — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
