### PR TITLE
NAS-111693 / 12.0 / fix enclosure.sync_zpool

### PR DESCRIPTION
**Pull request by yocalebo**
1. No reason to call `truenas.get_chassis_hardware` for every zpool on system so call it outside for loop.
2. `disk.label_to_disk` is abysmally slow when it has to run `geom.scan()`, instead use new `label_to_dev_disk_cache` method to essentially make this portion of the method instant.
3. `_get_ses_slot_for_disk` calls `enclosure.query` but we already enumerate the enclosures at the top of this method in the `encs` variable. Use the built-in `find_device_slot` instead to prevent unnecessary `enclosure.query` calls for every disk on every zpool.

Before changes `enclosure.sync_zpool` was taking ~5mins+ on M60 with 417 disks.
After changes `enclosure.sync_zpool` is taking ~21seconds on M60 with 417 disks.

### CODE REVIEW

**Review by rick-mesta — APPROVED** [review]
LGTM; I'll wait on @themylogin 's review before merge 👍🏼

**Comment by rick-mesta** [comment]
@themylogin: ping

**Review by themylogin — APPROVED** [review]

**Comment by rick-mesta** [comment]
@themylogin: Thx Vlad 👍🏼

**Comment by themylogin** [comment]
backport

**Pull request merged**
