### PR TITLE
NAS-111179 / 21.10 / improve gathering DMI information

### PR DESCRIPTION
**Pull request by yocalebo**
On `middlewared` service start up or at boot time, 7 subprocess'es run back-to-back to fill out the DMI information. This does not scale well when the system is very busy. `dmidecode` allows you to specify all  the "types" at once so we can gather this information via 1 subprocess which is a 7x improvement in that respect. Furthermore, separate the dmi related methods to their own module in `system_/dmi.py`.

### CODE REVIEW

**Review by themylogin — CHANGES_REQUESTED** [review]
`SystemService._parse_dmi` is a great candidate to add a few unit tests! Check out `src/middlewared/middlewared/pytest/unit/alert/source/test_ipmi_sel.py` for an example.

**Comment by yocalebo** [comment]
Are the unit tests in `middlewared/pytest` run in any automated way. More importantly, if they fail is anyone notified?

**Comment by themylogin** [comment]
@yocalebo @rick-mesta right now developers have to run them manually, but last week I started another attempt to integrate them into Jenkins pipeline.

**Review by themylogin — CHANGES_REQUESTED** [review]
We use pytest instead of unittest. It is run as `pytest src/middlewared/middlewared/pytest/unit/plugins/system/test_dmi.py ` and test declarations are a little bit different.

**Review by themylogin — APPROVED** [review]
Thank you!

**Pull request merged**
