### PR TITLE
Fix `system.info` schema

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Review by yocalebo — COMMENTED** [review]
This should be set to a bool when it gets to "Error Correction Type".

**Comment by themylogin** [comment]
@yocalebo if `Error Correction Type` is not present in the dmidecode output (e.g. if I run it on VirtualBox) then this variable stays an empty string which contradicts schema declaration and fails in debug mode.

**Comment by yocalebo** [comment]
> @yocalebo if `Error Correction Type` is not present in the dmidecode output (e.g. if I run it on VirtualBox) then this variable stays an empty string which contradicts schema declaration and fails in debug mode.

Then add an "or not sect" on the last elif line and then please update the unit test with the text output from your virtual box machine so we can catch it in future 😄

**Comment by themylogin** [comment]
@yocalebo we already have such entities among test cases. I updated unit test.

**Review by yocalebo — APPROVED** [review]

**Comment by themylogin** [comment]
backport

**Pull request merged**
