### PR TITLE
Remove AFP tests

### PR DESCRIPTION
**Pull request by anodos325**

### CODE REVIEW

**Comment by themylogin** [comment]
@anodos325 what if we adapt these tests to create AFP shares using new Samba API and continue using OS X to test if AFP protocol still works?

**Comment by anodos325** [comment]
AFP protocol is gone with netatalk removal.

**Comment by anodos325** [comment]
But you're right that we need some tests for functionality specific to the `afp` tag.

**Comment by anodos325** [comment]
Closing PR because this master runs tests against 13-stable.

**Pull request closed without merging**
