### PR TITLE
NAS-116822 / 13.0 / chelsio_adapter_config: Fix pciconf parsing for 13

### PR DESCRIPTION
**Pull request by ghost**
`pciconf -l` output has changed in FreeBSD 13.  Adapt accordingly.

### CODE REVIEW

**Comment by freqlabs** [comment]
time 0:15

**Review by amotin — COMMENTED** [review]
I think there would be better to add spaces before "vendor=", since there are "subvendor=".

**Comment by rick-mesta** [comment]
Holding off on merge until stable is taking in U2 bits -- unless you guys feel this fix **_should_** make it into U1

**Comment by yocalebo** [comment]
@rick-mesta this needs to go into U1

**Comment by amotin** [comment]
@rick-mesta The script is obviously broken for 13.  I don't see any reason to delay this.

**Comment by rick-mesta** [comment]
ok... thx for the feedback, fellas -- I'll update JIRA

**Pull request merged**
