### PR TITLE
NAS-108987 / 21.06 / Unable to import pool - pool shows up in dialog import list, but fails at zfs.find_import

### PR DESCRIPTION
**Pull request by dhiltonp**
This is just a quick hack to look for importable pools on whole disks, too.

See discussion here: https://jira.ixsystems.com/browse/NAS-108987

### CODE REVIEW

**Comment by dhiltonp** [comment]
Tested locally, works for me.

**Comment by dhiltonp** [comment]
Hold that, I bumped in to another issue.

**Comment by dhiltonp** [comment]
I initially was passing `/dev/disk/by-uuid` as the 2nd paramater, zpool status showed:

	NAME                     STATE     READ WRITE CKSUM
	tank                     ONLINE       0     0     0
	  mirror-0               ONLINE       0     0     0
	    1824969785541290475  ONLINE       0     0     0
	    sdb                  ONLINE       0     0     0

The issue is that TrueNAS doesn't realize that `1824969785541290475` is `/dev/sda`, and so `/dev/sda` shows up as available for use in other vdevs.

I've updated the code to pass `/dev`...

I tested on the command line with multiple -d switches and the path found first (left to right) is the one that is used, so uuids are used for partitions and disk names are used for whole disks.

**Comment by dhiltonp** [comment]
With the current version, I do get several "Error getting pool data" dialogs appearing over the screen; I don't know what they mean. I searched for the text and was unable to find it.

image

Also note that `tank` is listed multiple times. It's listed 4 times. The pool has 2 disks, and the error dialog appears 8 times.

On subsequent refreshes the pool only shows up once.

**Comment by william-gr** [comment]
You probably get those because whole disk ZFS pools are not supported by our middleware.

It is very likely many operations would fail, including replacing a disk because the lack of space.

**Comment by dhiltonp** [comment]
It's clear that importing pools with vdevs that use whole disks is not currently supported. That's an excellent thing to discuss.

The previous behavior is wrong - just getting a stack trace with no explanation.

At a minimum, the pool could be shown in the import list, but the import could fail with an error like `Cannot import pools with vdevs that use whole disks; vdev devices must be partitions.` 

This seems wrong; only a fraction of what TrueNAS provides is vdev management. If nothing else, the user can manage the vdev via the command line, using TrueNAS for other operations.

That's what this PR allows.

Another option beyond what I have in this PR is to allow the import, but warn the user `Disk management for vdevs that use whole disks instead of partitions is not fully supported.`

I don't know what operations don't work. I suspect that all operations would work, so long as the new device is larger than the old (to make room for the overhead of the partition table).

**Comment by william-gr** [comment]
This sounds like a bigger feature request than just allowing a pool to be imported.

There are many assumptions that are made in middleware about how the pool is set up.
If we allow pools like that to be imported than we are automatically in the hook for fixing all the issues it will imply along the way.

**Comment by dhiltonp** [comment]
If that's true, then the only importable ZFS pools would be ones created by TrueNAS.

That seems short-sighted.

It's ok to have soft boundaries where you say "we don't support this, but we accept contributions." 

In this case "we do our testing on pools created by TrueNAS. You can import other pools but you may run in to issues with volume management. PRs improving TrueNAS are welcome :)"

**Comment by william-gr** [comment]
Sorry, where did I say anything different?

**Comment by dhiltonp** [comment]
I interpreted "If we allow pools like that to be imported than we are automatically in the hook for fixing all the issues it will imply along the way" as you giving a reason to not accept the PR.

**Comment by william-gr** [comment]
No. I just meant there may be implications and before accepting the PR we need to make sure at least some basic functionalities are working. Its no good if we change this to allow importing that kind of pool and a lot of other places are failing (based on your screenshot that may be the case).

**Comment by sonicaj** [comment]
Closing this PR as changes introduced here will be catered for in https://github.com/truenas/middleware/pull/6856.

**Pull request closed without merging**
