### PR TITLE
NAS-117927 / 22.12 / Remove dead smartctl code and fix functional tests

### PR DESCRIPTION
**Pull request by yocalebo**
The code that was removed is freeBSD specific and would have never worked on SCALE the way it was currently written. Furthermore, these hba drivers are pretty legacy while most don't even have in-kernel drivers. They have to be installed manually....which is also something we don't support.

Fixes employed in this PR:
1. remove dead code that was freeBSD specific
2. simplify `get_smartctl_args` now that most of it has been removed
3. fix the functional tests

### CODE REVIEW

**Review by themylogin — CHANGES_REQUESTED** [review]
We don't even need `devices` in `context` right now

**Comment by yocalebo** [comment]
> We don't even need `devices` in `context` right now

We actually do. I can remove a call to `await run(` because `devices` has a key that will be `USB` if it's a USB device.

**Review by themylogin — COMMENTED** [review]
Cool! But doesn't `test_get_disk__unknown_usb_bridge` need updating too then?

**Comment by yocalebo** [comment]
> Cool! But doesn't `test_get_disk__unknown_usb_bridge` need updating too then?

Yep sorry, I was too slow. I've updated it now.

**Review by themylogin — CHANGES_REQUESTED** [review]
Sorry for nitpicking, but second question: do we even need `get_storage_devices_topology` now? I see there is only one remaining call, it can be perfectly substituted by the same `get_disks` method too

**Comment by yocalebo** [comment]
> Sorry for nitpicking, but second question: do we even need `get_storage_devices_topology` now? I see there is only one remaining call, it can be perfectly substituted by the same `get_disks` method too

It's no problem and you're right. I just missed it. I'll fix and remove `get_storage_devices_topology' altogether

**Review by themylogin — APPROVED** [review]
Thank you!

**Pull request merged**
