### PR TITLE
NAS-111042 / 12.0 / pool.dataset: optimized create/update operations

### PR DESCRIPTION
**Pull request by rkojedzinszky**
With these changes, pool.dataset create/update operations perform constant in time. This improves speed when there are lot of sibling datasets.

### CODE REVIEW

**Comment by sonicaj** [comment]
@rkojedzinszky can you please rebase your changes from 12 stable branch again ? Thank you

**Comment by rkojedzinszky** [comment]
> @rkojedzinszky can you please rebase your changes from 12 stable branch again ? Thank you

@sonicaj Done. As I see, the master branch will not need this change.

**Comment by sonicaj** [comment]
@rkojedzinszky the flake8 test failed, can you please address the lint issue ( https://github.com/truenas/middleware/pull/6955/checks?check_run_id=2839147293 ) ? Thank you

**Comment by rkojedzinszky** [comment]
> @rkojedzinszky the flake8 test failed, can you please address the lint issue ( https://github.com/truenas/middleware/pull/6955/checks?check_run_id=2839147293 ) ? Thank you

@sonicaj Fixed.

**Review by sonicaj — APPROVED** [review]
@rkojedzinszky thank you for your contribution :)

**Review by rick-mesta — APPROVED** [review]

**Pull request merged**
