### PR TITLE
NAS-113982 / 13.0 / add geom plugin and cache geom/xml info

### PR DESCRIPTION
**Pull request by yocalebo**
Add a private `GeomCache` plugin that caches the formatted geom information for disks as well as cache the raw xml data.

NOTE: These are not plumbed in or used anywhere at the moment. Later PR's will use these.

### CODE REVIEW

**Review by themylogin — CHANGES_REQUESTED** [review]
No need for an extra thread, Check out how https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/plugins/disk_/smartctl.py#L14 works - basically, the same thing

**Comment by yocalebo** [comment]
> No need for an extra thread, Check out how https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/plugins/disk_/smartctl.py#L14 works - basically, the same thing

What's wrong with another thread?

**Comment by themylogin** [comment]
@yocalebo why increase thread count in already bloated middleware just to sleep 99.99% of the time if we can avoid that?

**Comment by yocalebo** [comment]
> @yocalebo why increase thread count in already bloated middleware just to sleep 99.99% of the time if we can avoid that?

That's a valid point. I'll fix, after I get back from vacation🙂

**Review by themylogin — APPROVED** [review]

**Review by rick-mesta — APPROVED** [review]

**Pull request merged**
