### PR TITLE
NAS-110209 / 21.06 / Move rrdcached journal and nslcd cache from boot pool

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by ChrisCheney** [comment]
I added the above patch to my 21.02 install and noticed that /tmp/cache/nscd didn't exist after reboot but that the symlink to it did. I suspect /tmp was not yet mounted by the time the middleware code ran running the mkdir on /tmp/cache/nscd.

**Comment by themylogin** [comment]
@ChrisCheney thank you! systemd was removing everything from /tmp after middleware startup, we fixed that

**Comment by themylogin** [comment]
@yocalebo can you please take a look at this?

**Review by yocalebo — COMMENTED** [review]
Do you know how large these directories can grow? We have had past problems where `tmpfs` will be filled up to 100% and then lots of other things begin to break.

**Comment by themylogin** [comment]
@yocalebo I can't think of a case where `nscd` cache will grow past a few megabytes

**Comment by yocalebo** [comment]
> @yocalebo I can't think of a case where `nscd` cache will grow past a few megabytes

Sure, I'm mostly wondering about rrdcached.

**Comment by themylogin** [comment]
@yocalebo rrdcached journal is being moved to the system dataset

**Review by yocalebo — APPROVED** [review]

**Pull request merged**
