### PR TITLE
NAS-133159 / 25.04 / Expose idmap

### PR DESCRIPTION
**Pull request by william-gr**
These might be important for users to know which uid/gid to use when sharing data between host and container.

### CODE REVIEW

**Comment by anodos325** [comment]
Can you be more specific than Idmap? This terminology is used in many unrelated things (winbind, sssd, nfs, etc). Perhaps ContainerIdmap

**Comment by william-gr** [comment]
@anodos325 how about `userns_idmap`?

**Comment by william-gr** [comment]
@Qubad786 @anodos325 ping

**Comment by anodos325** [comment]
> @Qubad786 @anodos325 ping

Yup. That works.

**Comment by anodos325** [comment]
Are we not going to do any validation on these ranges?

**Comment by william-gr** [comment]
@anodos325 this is only for querying what is in incus, we don't allow setting it, unsure if we need to do any validation in this case?

**Comment by anodos325** [comment]
> @anodos325 this is only for querying what is in incus, we don't allow setting it, unsure if we need to do any validation in this case?

Okay. That makes sense. Are we going to raise any alerts about incus configurations (wouldn't want that in query method of course), or will this kind of be a user free-for-all?

**Comment by william-gr** [comment]
@anodos325 had not given any thought about it so far. We could potentially have a polling alert to do some checks but I am still unsure what to check for. Perhaps running through our usual validation method to report any unsupported config?

**Review by anodos325 — APPROVED** [review]

**Pull request merged**
