### PR TITLE
NAS-111447 / 21.08 / Add POSIX_HOME preset

### PR DESCRIPTION
**Pull request by anodos325**

### CODE REVIEW

**Comment by anodos325** [comment]
This time with the correct bug number

**Review by rick-mesta — APPROVED** [review]

**Comment by undsoft** [comment]
Bump.

**Comment by anodos325** [comment]
Will address tomorrow. Today was spent putting out fires with clustering. May rework so that we have a proper CRUD API for ACL templates and keep around the default acl stuff as a legacy wrapper. So a little more work, but a little more standard and better for future.

**Comment by rick-mesta** [comment]
@anodos325: ping... `21.08` train looking awfully close 😬

**Pull request merged**
