### PR TITLE
NAS-116717 / 22.12 / Fix `disk.query` event being sent with `disk_` key prefixes

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by themylogin** [comment]
time 1:00

**Comment by anodos325** [comment]
I vaguely recall that there was a reason Caleb was using the datastore plugin.

**Comment by themylogin** [comment]
time 1:00

**Review by sonicaj — APPROVED** [review]

**Review by yocalebo — CHANGES_REQUESTED** [review]
disk.query is slow on large systems which is why I didn't use it. A KeyError happened on 13 but was happening because when we formatted the disks, a disk event would call this method which would race before geom formatting would finish. Also, this method runs without KeyErrors 100% of the time when called in isolation.

**Comment by themylogin** [comment]
@yocalebo was that KeyError fixed somewhere?

**Comment by yocalebo** [comment]
> @yocalebo was that KeyError fixed somewhere?

Yeah, I was able to reproduce and confirm it was fixed when you and I added the event blocking context manager.

**Pull request closed without merging**
