### PR TITLE
NAS-132097 / 25.04 / Add a migration to remove unused k8s table fields

### PR DESCRIPTION
**Pull request by sonicaj**

### CODE REVIEW

**Comment by themylogin** [comment]
What will happen with 24.04 -> 25.04 upgrades?

**Comment by sonicaj** [comment]
Nothing, these columns are not being used ?

**Review by yocalebo — APPROVED** [review]

**Comment by themylogin** [comment]
I mean, were they never used?

**Comment by sonicaj** [comment]
They were used when we had k8s but when we removed it, the table is not required anymore - we just want to know what pool was configured at the point and all other columns are redundant.

**Pull request merged**
