### PR TITLE
ZFSDatasetService: use id optimization in more cases

### PR DESCRIPTION
**Pull request by rkojedzinszky**
For example, if called from PoolDatasetService.query, where filter list contains expressions to exclude system datasets.

### CODE REVIEW

**Comment by william-gr** [comment]
Thanks for the patch but I am curious where you saw an usage like that.

Proper usage would probably be `["id", "in", ["dataset1", "dataset2"]]`

**Comment by rkojedzinszky** [comment]
@william-gr i did not mean such invocations, and even, my solution is broken. The intent is to use `datasets` filter even if more than one filter is passed to speed up lookups. I'll force-push a more correct fix.

**Comment by rkojedzinszky** [comment]
For example, this is called when an iSCSIextent is created, and in some cases, extra filters may be added to exclude system datasets. In that case, no optimization was made.

**Review by sonicaj — COMMENTED** [review]
@rkojedzinszky can you please clarify your use case ? I am curious how you are planning on consuming this change especially since `zfs.dataset` is a private service ?

**Comment by rkojedzinszky** [comment]
> @rkojedzinszky can you please clarify your use case ? I am curious how you are planning on consuming this change especially since `zfs.dataset` is a private service ?

You are right, in master branch this might not be needed anymore. In 12-stable, pool.dataset.query adds more filter elements, which is handled different, that may cause all datasets to be retrieved. Then, I'll close this PR, but in 12-stable, it might be relevant.

**Comment by sonicaj** [comment]
That shouldn't be the case anymore in `truenas/12.0-stable` branch, please let me know otherwise. Thank you

**Comment by rkojedzinszky** [comment]
> That shouldn't be the case anymore in `truenas/12.0-stable` branch, please let me know otherwise. Thank you

Sure, I probably missed https://github.com/truenas/middleware/commit/8b5e322fa1792b1744a821056dc20b3bb2953fda. I was working on a tree pulled from a working truenas-12-u2, and there it was still needed.

**Pull request closed without merging**
