### PR TITLE
NAS-115355 / 22.12 / fix test_400_service.py

### PR DESCRIPTION
**Pull request by yocalebo**
1. The test results printed the service id (an integer) instead of the service name.  Now it prints service name
(i.e. `api2/test_400_service.py::test_02_get_service_info_for[4] PASSED` to `api2/test_400_service.py::test_01_enable_service[cifs] PASSED`)
2. It chose (randomly) 4 services to actually start which doesn't make much sense so I removed that because
`cifs` is handled in the `test_420_smb.py` script
`iscsitarget` is handled in the `test_260_iscsi.py` script
`snmp` is handled in the `test_440_snmp.py` script
`rsync` is handled in the `test_380_rsync.py` script
3. dramatically simplify the file and remove unnecessary code
4. rename this to `test_400_enable_disable_services.py` since that's what it's actually doing

### CODE REVIEW

**Comment by themylogin** [comment]
So this module does not test services being able to start anymore?

**Comment by yocalebo** [comment]
> So this module does not test services being able to start anymore?

No it was randomly choosing 4 services that really didn't test anything. The other integration tests for those services start/stop the service appropriately.

**Comment by themylogin** [comment]
> > So this module does not test services being able to start anymore?
> 
> No it was randomly choosing 4 services that really didn't test anything. The other integration tests for those services start/stop the service appropriately.

I don't see any randomness in the original code, can you please elaborate?

**Comment by yocalebo** [comment]
Why did we randomly choose `cifs, iscsitarget, rsync, snmp`. What does it accomplish by starting those here?

**Comment by themylogin** [comment]
@yocalebo so by "randomness" you mean our wonderful QE team approach to developing tests, I get it.

Do we already have other integration tests that verify that each of these services is able to start in default configuration? If not, I would like to ask you to add them so we don't lose at least those.

Also it would be better to group `test_01_enable_service` and `test_02_verify_service_was_enabled` into one test case, same for disabing. What sense does it have to split this into two cases?

**Comment by yocalebo** [comment]
> @yocalebo so by "randomness" you mean our wonderful QE team approach to developing tests, I get it.
> 
> Do we already have other integration tests that verify that each of these services is able to start in default configuration? If not, I would like to ask you to add them so we don't lose at least those.
> 
> Also it would be better to group `test_01_enable_service` and `test_02_verify_service_was_enabled` into one test case, same for disabing. What sense does it have to split this into two cases?

Okay sounds good, I did verify that those services are tested elsewhere.
`cifs` is handled in the various `test_420_smb.py` script
`iscsitarget` is handled in the `test_260_iscsi.py` script
`snmp` is handled in the `test_440_snmp.py` script
`rsync` is handled in the `test_380_rsync.py` script

**Review by themylogin — APPROVED** [review]

**Pull request merged**
