### PR TITLE
NAS-118152 / 22.12 / set CPU governor to performance mode always

### PR DESCRIPTION
**Pull request by yocalebo**

### CODE REVIEW

**Review by themylogin — APPROVED** [review]

**Comment by SuperQ** [comment]
Hmm, that Jira issue isn't public. Can you post a "why" this is being done?

I personally would like to keep my system in the default powersave mode, which better adjusts system performance based on the intel_pstate driver.

**Comment by kmoore134** [comment]
In our testing it made a significant difference in overall system performance and throughput. We may allow it to be tuned back to other profiles later though, for the few who do not care about performance.

**Comment by SuperQ** [comment]
"Don't care about performance" is a bit projecting assumptions about what people want.

**Comment by kmoore134** [comment]
Ha, let me clarify then. Those who do not require max performance 100% of the time.

**Pull request merged**
