### PR TITLE
NAS-131611 / 25.04 / Fix crash due to ProductType not being JSON serializable

### PR DESCRIPTION
**Pull request by anodos325**

### CODE REVIEW

**Review by yocalebo — COMMENTED** [review]
This change doesn't make sense. We shouldn't be serializing the entire class.

**Review by yocalebo — CHANGES_REQUESTED** [review]
I see now. This is similar to what I asked to be done.

```
@dataclass(slots=True, frozen=True)
class ProdTypes:
     SCALE: str = 'SCALE'
     SCALE_ENTERPRISE: str = 'SCALE_ENTERPRISE'


ProductType = ProdTypes()

**Comment by sonicaj** [comment]
Oops, just saw this :P 
Made a PR https://github.com/truenas/middleware/pull/14625

**Comment by yocalebo** [comment]
> Oops, just saw this :P 
> 
> Made a PR https://github.com/truenas/middleware/pull/14625

If you revert the changes in your PR and do what I said in my last comment on this PR, I'll approve yours so we can get it merged

**Comment by sonicaj** [comment]
@yocalebo updated

**Comment by yocalebo** [comment]
Fixed in https://github.com/truenas/middleware/pull/14625

**Pull request closed without merging**
