### PR TITLE
NAS-116725 / 22.02.3 / Show only block NVMe devices in R50 enclosures

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by themylogin** [comment]
time 0:30

**Comment by william-gr** [comment]
Can you educate me what a nvme device that is not a block looks like?

**Comment by themylogin** [comment]
@william-gr `/dev/nvme1` is a device that has `subsystem == "nvme"`. `/dev/nvme1n1` is a device that has `subsystem == "block"`. `disk.query` returns `nvme1n1` devices, not `nvme1`.

**Review by william-gr — APPROVED** [review]
Makes sense, and that will make it match the disk to show in enclosure screen from UI

**Pull request merged**
