### PR TITLE
NAS-104989 / 22.02 / Return IP network if schema wants an IP network

### PR DESCRIPTION
**Pull request by themylogin**
time 1:00

### CODE REVIEW

**Review by yocalebo — CHANGES_REQUESTED** [review]
The original ticket was for CORE. Have you tested that this even applies to SCALE?

**Comment by themylogin** [comment]
@yocalebo this ticket fixes a high-level validation issue that will benefit every middleware subsystem. There are no NFS-related changes here.

**Comment by yocalebo** [comment]
> @yocalebo this ticket fixes a high-level validation issue that will benefit every middleware subsystem. There are no NFS-related changes here.

The original ticket was for undefined behavior on freeBSD's `mountd` because of how we were generating the exports file. So this is indirectly changing NFS share creating/update behavior. I ask about SCALE because the webUI (on nightlies) correctly formats the payload on the front-end so it is working "by mistake". I agree with the changes, btw. I just wish there was a little more context because this change affects every single API endpoint that uses the `IPAddr` validator while the original ticket was specific to CORE's `mountd` and the exports file (which doesn't even exist on SCALE).

**Review by yocalebo — APPROVED** [review]

**Comment by themylogin** [comment]
@yocalebo there are 3 consumers of `IPAddr(..., network=True)`, all of them actually need a network so converting from `IP` to `IP/32` won't break anything

**Pull request merged**
