### PR TITLE
NAS-122173 / 23.10 / Remove DynDNS, OpenVPN, rsyncd, WebDAV

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by themylogin** [comment]
No related test failures found https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/API%20Tests%20-%20TrueNAS%20SCALE%20with%20middleware%20reinstalled%20from%20a%20branch%20Incremental/856/#showFailuresLink

**Review by yocalebo — APPROVED** [review]
Make the sure the migration changes are going to work since you've got other PR's that also add migrations.

**Comment by themylogin** [comment]
@yocalebo I don't understand your request, `cf91fa3d0696` is indeed the head migration in the current master

**Comment by themylogin** [comment]
time 4:00

**Pull request merged**
