### PR TITLE
NAS-131330 / 25.04 / Better error handling for bad storj bucket name

### PR DESCRIPTION
**Pull request by creatorcary**
Currently the returned `CallError` is "An error occurred (InvalidBucketName) when calling the CreateBucket operation: The specified bucket is not valid." To save the user some research, we can clarify this message to the `ValidationError` "Bucket name can only contain lowercase letters, numbers, and hyphens" which is verbatim in the [storj documentation](https://storj.dev/support/object-browser#:~:text=The%20bucket%20name%20can%20only%20contain%20lowercase%20letters%2C%20numbers%2C%20and%20hyphens.) or "The bucket name must be between 3-63 characters in length and cannot contain uppercase."

[s3 bucket naming rules](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html) (we do not enforce them all!)

We should ask UI to render these errors as red validation text as per the submitted ticket.

validation_bucke+
validation_BUCKET

### CODE REVIEW

**Comment by william-gr** [comment]
I still dont quite understand why we dont validate the bucket name prior to actually trying to make the network request?

**Comment by yocalebo** [comment]
> I still dont quite understand why we dont validate the bucket name prior to actually trying to make the network request?

The idea is that we don't maintain a list of requirements on our side that the s3 api already enforces. The moment we enforce these, s3 will change their requirements and then we'll have to update ours to match theirs etc.

**Comment by creatorcary** [comment]
I should note that some of the hyper-specific naming rules are not enforced by the storj api. For example, naming a bucket "amzn-s3-demo-bucket" is allowed.

**Review by aiden3c — APPROVED** [review]
LGTM!

**Review by themylogin — APPROVED** [review]

**Pull request merged**
