### PR TITLE
NAS-116643 / 13.0 / Fix `{uuid}` device identifiers

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by themylogin** [comment]
time 12:00

**Comment by rick-mesta** [comment]
@sonicaj / @anodos325 / @Qubad786: would one of you fellas take a look at this PR, please ?

**Review by william-gr — APPROVED** [review]
I don't think many people know this code other than Caleb and me (or the remaining of it).
I dont know the performance implications here of using PART vs DISK and iterating providers but the change looks reasonable to me.

Need to make sure Caleb reviews this when he is back.

**Comment by william-gr** [comment]
@yocalebo just tagging you for review (after merge) for when you get back next week.

**Comment by themylogin** [comment]
@william-gr this code is only executed if a disk drive does not report its serial number — weird USB dongles, weird hypervisors... I can’t imagine such a system with 100 or 1000 drives where performance implications might occur.

**Comment by william-gr** [comment]
Makes sense

**Pull request merged**
