### PR TITLE
NAS-112300 / 21.10 / Remove zilstat dtrace script

### PR DESCRIPTION
**Pull request by freqlabs**
On Linux we don't have dtrace but we do have a zil kstat in /proc that
provides the information needed for our SNMP MIBs.

Remove the useless script and adapt snmp-agent.py to use the kstat
instead.  The MIB names and descriptions are unchanged to maintain
compatibility.

Jira: NAS-112300

### CODE REVIEW

**Comment by freqlabs** [comment]
Marked WIP until I have finished testing this.

**Comment by yocalebo** [comment]
While you're here 😄 Removing the `if osc.` checks in that file would be nice to "clean" it up a bit. You can rename the `parse_Kstat_linux` method to just `parse_kstat` since this repo is SCALE only.

**Comment by freqlabs** [comment]
I think this MIB is broken in CORE. I can't find it with snmpwalk in either CORE or SCALE, just these
```
FREENAS-MIB::zfsArcSize.0 = Gauge32: 2503812
FREENAS-MIB::zfsArcMeta.0 = Gauge32: 377338
FREENAS-MIB::zfsArcData.0 = Gauge32: 2122375
FREENAS-MIB::zfsArcHits.0 = Gauge32: 1493723178
FREENAS-MIB::zfsArcMisses.0 = Gauge32: 66024
FREENAS-MIB::zfsArcC.0 = Gauge32: 2624223
FREENAS-MIB::zfsArcP.0 = Gauge32: 2018664
FREENAS-MIB::zfsArcMissPercent.0 = STRING: 0.0004591794871089405
FREENAS-MIB::zfsArcCacheHitRatio.0 = STRING: 100.00
FREENAS-MIB::zfsArcCacheMissRatio.0 = STRING: 0.00
FREENAS-MIB::zfsL2ArcHits.0 = Counter32: 0
FREENAS-MIB::zfsL2ArcMisses.0 = Counter32: 0
FREENAS-MIB::zfsL2ArcRead.0 = Counter32: 0
FREENAS-MIB::zfsL2ArcWrite.0 = Counter32: 0
FREENAS-MIB::zfsL2ArcSize.0 = Gauge32: 0
```

**Comment by freqlabs** [comment]
https://jira.ixsystems.com/browse/NAS-112346

**Comment by freqlabs** [comment]
Ok I have been able to test and confirm this is working.

**Comment by yocalebo** [comment]
retest this please

**Review by themylogin — APPROVED** [review]

**Pull request merged**
