### PR TITLE
NAS-114821 / 22.02.1 / Abort erroneous websocket connections and handle connection aborts in websocket client

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by themylogin** [comment]
time 8:00

**Review by yocalebo — APPROVED** [review]
I can confirm this fixes the problem. Just 1 nit-pick though. If `reason=None` then the log message just shows `reason=b''`. Maybe make it default to `Not provided` or something?

**Review by yocalebo — CHANGES_REQUESTED** [review]
Hold on, I'm seeing the child processes are hanging onto the memory and not releasing it.

**Review by yocalebo — APPROVED** [review]
Okay this fixes the immediate problem of causing a deadlock with our process pool so I'll approve it. I'll open up another ticket for the child processes not releasing memory.

**Pull request merged**
