### PR TITLE
NAS-114228 / 22.02 / zettarepl.create_recursive_snapshot_with_exclude

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Review by sonicaj — COMMENTED** [review]
How about having this under `zfs.snapshot` namespace ?

**Comment by themylogin** [comment]
This imports `zettarepl` and I prefer to keep such methods in a special place

**Comment by sonicaj** [comment]
@themylogin we can call zettarepl plugin internally from the `zfs.snapshot` namespace ?

**Comment by sonicaj** [comment]
It's just that, from consumer perspective - it makes more sense to be consuming this from `zfs.snapshot` namespace

**Comment by themylogin** [comment]
Done, but internally it'll still be better to use zettarepl method directly to avoid using process pool

**Comment by themylogin** [comment]
time 0:30

**Review by sonicaj — APPROVED** [review]

**Pull request merged**
